### ISSUE TITLE
Dataset statistics inconsistency

### ISSUE THREAD

**Issue by nojhan** [IOHprofiler/IOHanalyzer#52]
When I upload the attached dataset to an 0414b26 instance, its overview statistics seem inconsistent.

The dataset is two runs of a single expe, with `Maximization = "F"` and loaded with the `MINIMZATION` option:
[expe_pop5.zip](https://github.com/IOHprofiler/IOHanalyzer/files/4354730/expe_pop5.zip)

Overview statistics:

|algId|DIM|funcId|runs|best reached|succ|budget|max evals used|worst recorded|worst reached|mean reached|median reached|
|------------|--|--|-|------|-|----|-|------|------|------|------------|
|AIon_pop5|50|24|2|633.76|1|5000|1|573.76|573.76|603.76|603.757941|

I don't understand why _"best_reached" > "worst_reached"_ and why _"max_evals_used" == 1_.

**Comment by Dvermetten** [comment]
Thank you for reporting this issue. 
I found that this is caused by some inconsistencies in capitalization within our functions for reading the info-files. We will fix this soon, but for now it should work if you use "maximization" instead of "Maximization".
Apologies for the inconvenience this issue has caused.

**Comment by nojhan** [comment]
This metadata is issued directly from IOH experimenter, should I post an
issue there also?

**Comment by Dvermetten** [comment]
I don't think there is a need to create a separate ticket on the experimenter, since this is something we need to handle in the analyzer.
